---
sap_storage_dict:
  hanadata:
    name: 'hanadata'
    directory: '/hana/data'
    vg: 'hanadatavg'
    lv: 'hanadatalv'
    pv: ["/dev/nvme5n1", "/dev/nvme6n1"]
    numluns: '1'
    stripesize: '256'
  # LVM striped partition
  hanalog:
    name: 'hanalog'
    directory: '/hana/log'
    vg: 'hanalogvg'
    lv: 'hanaloglv'
    pv: ["/dev/nvme7n1", "/dev/nvme8n1"]
    numluns: '2'
    stripesize: '32'
  hanashared:
    name: 'hanashared'
    directory: '/hana/shared'
    vg: 'hanasharedvg'
    lv: 'hanasharedlv'
    pv: ["/dev/nvme9n1"]
    numluns: '1'
    stripesize: ''
  usrsap:
    name: 'usrsap'
    directory: '/usr/sap'
    vg: 'usrsapvg'
    lv: 'usrsaplv'
    pv: ["/dev/nvme10n1"]
    numluns: '1'
    stripesize: ''
  backup:
    name: 'backup'
    directory: '/backup'
    vg: 'backupvg'
    lv: 'backuplv'
    pv: ["/dev/nvme11n1"]
    numluns: '1'
    stripesize: ''
