---
- name: SAP HANA cluster
  hosts: hana
  remote_user: cloudadmin
  become: true
  become_user: root
  vars:
    # SAPHahaSR-angi
    use_sap_hana_sr_angi: false
    # is_primary is selected so that tasks that need to be issued one are honoured correctly
    is_primary: "{{ ansible_play_hosts[0] == inventory_hostname }}"
    primary_hostname: "{{ ansible_play_hosts[0] }}"
    # Azure fencing specific vars
    azure_identity_management:  # use 'spi' (service principal) or 'msi' (managed identity)
    # Azure fencing - SPN related variables
    spn_application_id:
    spn_application_password:
    # corosync variables
    crypto_hash: sha1
    crypto_cipher: aes256
    # Define some names in a central place
    rsc_socat: "rsc_socat_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}"
    rsc_saphanactl: "rsc_SAPHanaCtl_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}"

  handlers:
    - name: Restart systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start pacemaker
      ansible.builtin.systemd:
        name: pacemaker
        state: started
        enabled: true

  pre_tasks:
    - name: Detect cloud platform
      ansible.builtin.include_tasks:
        ./tasks/detect-cloud-platform.yaml

    - name: Load SAP HANA variables
      ansible.builtin.include_vars: ./vars/hana_vars.yaml

    - name: Set HANA var names
      ansible.builtin.set_fact:
        ms_saphana: "msl_SAPHanaCtl_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}"
      when:
        - not use_sap_hana_sr_angi | bool

    - name: Set HANA Angi vars
      ansible.builtin.set_fact:
        ms_saphana: "mst_SAPHanaCtl_{{ sap_hana_install_sid }}_HDB{{ sap_hana_install_instance_number }}"
      when:
        - use_sap_hana_sr_angi | bool

  tasks:
    - name: Base Cluster Configuration [azure]
      ansible.builtin.include_tasks: ./tasks/azure-cluster-bootstrap.yaml
      when:
        - cloud_platform_is_azure
      tags: bootstrap

    - name: Base Cluster Configuration [aws]
      ansible.builtin.include_tasks: ./tasks/cluster-bootstrap.yaml
      when:
        - cloud_platform_is_aws
      tags: bootstrap

    - name: Base Cluster Configuration [gcp]
      ansible.builtin.include_tasks: ./tasks/cluster-bootstrap.yaml
      when: cloud_platform_is_gcp
      tags: bootstrap

    - name: Add HANA to cluster [azure]
      ansible.builtin.include_tasks: ./tasks/azure-cluster-hana.yaml
      when:
        - cloud_platform_is_azure
        - is_primary
      tags: hana_cluster

    - name: Add HANA to cluster [aws]
      ansible.builtin.include_tasks: ./tasks/cluster-hana.yaml
      when:
        - cloud_platform_is_aws
        - is_primary

    - name: Add HANA to cluster [gcp]
      ansible.builtin.include_tasks: ./tasks/cluster-hana.yaml
      when:
        - cloud_platform_is_gcp
        - is_primary

    - name: Get cluster status after HANA cluster setup
      ansible.builtin.command:
        cmd: crm configure show
      register: crm_conf_show_after
      changed_when: false

    - name: Update HANA crm facts
      ansible.builtin.set_fact:
        crm_maintenance_mode: "{{ (crm_conf_show_after.stdout | regex_search('maintenance-mode=([a-z]*)', '\\1'))[0] | default('unknown') }}"
        stonith_enabled: "{{ (crm_conf_show_after.stdout | regex_search('stonith-enabled=([a-z]*)', '\\1'))[0] | default('false') }}"
        stonith_timeout: "{{ crm_conf_show_after.stdout | regex_search('stonith-timeout') }}"  # this should be variable!
        hana_resource: "{{ crm_conf_show_after.stdout | regex_search('primitive rsc_SAPHanaCtl_') }}"
        hana_clone: "{{ crm_conf_show_after.stdout | regex_search('ms ms._SAPHanaCtl_') }}"
        hana_topology_resource: "{{ crm_conf_show_after.stdout | regex_search('primitive rsc_SAPHanaTpg') }}"
        hana_topology_clone: "{{ crm_conf_show_after.stdout | regex_search('clone cln_SAPHanaTpg') }}"
        hana_filesystem_resource: "{{ crm_conf_show_after.stdout | regex_search('primitive rsc_SAPHanaFil_') }}"
        hana_filesystem_clone: "{{ crm_conf_show_after.stdout | regex_search('primitive cln_SAPHanaFil_') }}"
        ip_resource: "{{ crm_conf_show_after.stdout | regex_search('primitive rsc_ip_') }}"
        ip_nc: "{{ crm_conf_show_after.stdout | regex_search('primitive rsc_socat_') }}"
        ip_grp: "{{ crm_conf_show_after.stdout | regex_search('group g_ip_') }}"
        ip_colo: "{{ crm_conf_show_after.stdout | regex_search('colocation col_saphana_ip_') }}"
        cluster_order: "{{ crm_conf_show_after.stdout | regex_search('order ord_SAPHana_') }}"
        resource_stickiness: "{{ (crm_conf_show_after.stdout | regex_search('resource-stickiness=([0-9]*)', '\\1'))[0] }}"
        migration_threshold: "{{ (crm_conf_show_after.stdout | regex_search('migration-threshold=([0-9]*)', '\\1'))[0] }}"
      changed_when: false

    - name: Ensure maintenance mode is disabled
      ansible.builtin.command:
        cmd: >-
          crm configure
          property
          maintenance-mode=off
      register: cmd_crm_cpmm_output
      changed_when: cmd_crm_cpmm_output.rc != 0
      when:
        - (refreshed_crm_maintenance_mode is true ) or
          (refreshed_crm_maintenance_mode == 'on') or
          (refreshed_crm_maintenance_mode == 'unknown')
        - is_primary

    - name: Clean up MS resource
      ansible.builtin.command:
        cmd: >-
          crm resource
          cleanup
          {{ ms_saphana }}
      register: cmd_crm_rrmss_output
      changed_when: cmd_crm_rrmss_output.rc != 0
      when:
        - is_primary

    - name: Wait for cluster to be settled
      ansible.builtin.command:
        cmd: cs_wait_for_idle -s 5
      register: cmd_cwfi_output
      changed_when: cmd_cwfi_output.rc != 0
      when:
        - is_primary

    # For debug purpose only
    - name: Full cluster status at the end of deployment
      ansible.builtin.command:
        cmd: >-
          crm status
          full
      register: final_crm_status_full
      changed_when: false
      when:
        - is_primary
